<?php
// 取到当前页面的路径，用于后面计算其它资源的路径
$url = 'http://'.$_SERVER['SERVER_NAME'].$_SERVER["REQUEST_URI"];
$url = dirname(dirname(dirname(dirname(dirname(dirname(dirname(dirname($url))))))));

header('Content-type: application/json');
$json = '{
	"success": "TRUE",
	"payload": {
		"api_endpoints": {
			"get_navigation_build": "\/Navigation\/GetBuild\/init",
			"activity_enumerate_by_group": "\/Activity\/EnumerateByGroup\/init",
			"activity_get_engine_info": "\/Activity\/GetEngineInfo\/init",
			"activitygroup_getactivityinfo": "\/ActivityGroup\/GetActivityInfo\/init",
			"get_printable_info": "\/Activity\/GetPrintableInfo\/init",
			"adaptive_learning_get_log": "\/AdaptiveLearning\/GetLog\/init",
			"adaptive_learning_log": "\/AdaptiveLearning\/Log\/init",
			"biome_build_path": "\/Biome\/BuildPath\/init",
			"biome_enumerate": "\/Biome\/Enumerate\/init",
			"biome_enumerate_by_level": "\/Biome\/EnumerateByLevel\/init",
			"biome_get_facts_by_subject": "\/Biome\/GetFactsBySubject\/init",
			"biome_get_subjects": "\/Biome\/GetSubjects\/init",
			"event_log": "\/Event\/Log\/init",
			"event_queue": "\/Event\/Process\/init",
			"member_login": "\/Member\/Login\/init",
			"resource_enumerate": "\/Resource\/Enumerate\/init",
			"store_get": "\/Store\/Get\/init",
			"redeem_device_code": "\/TempAccount\/RedeemDeviceCode\/init",
			"assign_lesson": "\/User\/AssignLesson\/init",
			"get_lesson_recommendations": "\/User\/GetAssessmentLessonRecommendations\/init",
			"complete_biome_prize": "\/User\/CompleteBiomePrize\/init",
			"complete_biome_fact": "\/User\/CompleteBiomeFact\/init",
			"complete_biome_lesson": "\/User\/CompleteBiomeLesson\/init",
			"complete_biome_quiz": "\/User\/CompleteBiomeQuiz\/init",
			"complete_path_activity": "\/User\/CompletePathActivity\/init",
			"get_user_activity_audio": "\/User\/GetActivityAudio\/init",
			"get_user_activity_plays": "\/User\/GetActivityPlays\/init",
			"get_user_classroom_info": "\/User\/GetClassroomInfo\/init",
			"get_user_card_audio": "\/User\/GetCardAudio\/init",
			"get_user_analytics_info": "\/User\/GetAnalyticsInfo\/init",
			"get_user_family_info": "\/User\/GetFamilyInfo\/init",
			"guest_start_assessment": "\/Guest\/StartAssessment\/init",
			"guest_resume_assessment": "\/Guest\/ResumeAssessment\/init",
			"guest_submit_assessment_screen": "\/Guest\/SubmitAssessmentScreen\/init",
			"set_user_activity_audio": "\/User\/SetActivityAudio\/init",
			"set_user_card_audio": "\/User\/SetCardAudio\/init",
			"build_word_wall": "\/WordWall\/Build\/init",
			"basics_get_videos": "\/Basics\/GetVideos\/init",
			"basics_get_games": "\/Basics\/GetGames\/init",
			"user_addfavoriteactivity": "\/User\/AddFavoriteActivity\/init",
			"get_user_artwork": "\/User\/GetArtwork\/init",
			"user_start_activity": "\/User\/StartActivity\/init",
			"user_start_user_art_activity": "\/User\/StartUserArtActivity\/init",
			"save_user_art": "\/User\/SaveArt\/init",
			"user_end_activity": "\/User\/EndActivity\/init",
			"homepage_build_child": "\/Homepage\/BuildChild\/init",
			"homepage_build_parent": "\/Homepage\/BuildParent\/init",
			"user_cancel_activity": "\/User\/CancelActivity\/init",
			"user_start_assessment": "\/User\/StartAssessment\/init",
			"user_cancel_assessment_instance": "\/User\/ResetAssessmentInstance\/init",
			"user_submit_screen": "\/User\/SubmitAssessmentScreen\/init",
			"user_skip_assessment_skill": "\/User\/SkipAssessmentSkill\/init",
			"user_resume_assessment": "\/User\/ResumeAssessment\/init",
			"user_get_assessment_info": "\/User\/GetAssessmentInfo\/init",
			"user_get_assessment_skill_results": "\/User\/GetAssessmentSkillResults\/init",
			"user_get_language_info": "\/User\/GetLanguageInfo\/init",
			"user_get_subscription_info": "\/User\/GetSubscriptionInfo\/init",
			"assessment_get_lesson_recommendations": "\/Assessment\/GetLessonRecommendations\/init",
			"user_assign_lesson": "\/User\/AssignLesson\/init",
			"user_set_language": "\/User\/SetLanguage\/init",
			"holiday_share_by_email": "\/Holiday\/ShareByEmail\/init",
			"holiday_submit_feedback": "\/Holiday\/SubmitFeedback\/init",
			"holiday_start_holiday_card": "\/Holiday\/StartHolidayCard\/init",
			"holiday_get_overlay_info": "\/Holiday\/GetOverlayInfo\/init",
			"glossary_get_info": "\/AbcMouseWebServiceLayer\/GetGlossaryInfo\/init",
			"guest_submit_assessment_form": "\/Guest\/SubmitAssessmentForm\/init",
			"guest_get_assessment_skill_results": "\/Guest\/GetAssessmentSkillResults\/init",
			"user_get_assessment_notifications": "\/User\/GetAssessmentNotifications\/init",
			"user_dismiss_assessment_notifications": "\/User\/DismissAssessmentNotifications\/init",
			"parent_validate_password": "\/Parent\/ValidatePassword\/init",
			"animal_enumerate_zoo_animals": "\/Animal\/EnumerateZooAnimals\/init",
			"animal_enumerate_farm_animals": "\/Animal\/EnumerateFarmAnimals\/init",
			"animal_get_info": "\/Animal\/GetInfo\/init",
			"prize_wheel_win_prize": "\/PrizeWheel\/WinPrize\/init",
			"teacher_cancel_account": "\/Teacher\/CancelAccount\/init",
			"teacher_reinstate_account": "\/Teacher\/ReinstateAccount\/init",
			"teacher_get_purge_list_info": "\/Teacher\/IsInPurgeList\/init",
			"biome_get_graduation_info": "\/Biome\/GetGraduationInfo\/init",
			"user_complete_biome_path": "\/User\/CompleteBiomePath\/init",
			"parent_delete_child": "\/Parent\/DeleteChild\/init",
			"parent_get_children": "\/Parent\/GetChildrenInfo\/init",
			"parent_get_user_settings": "\/Parent\/GetUserSettings\/init",
			"parent_set_user_settings": "\/Parent\/SetUserSettings\/init",
			"parent_reset_child_path": "\/Parent\/ResetChildPath\/init",
			"parent_enumerate_child_pronunciations": "\/Parent\/EnumerateChildPronunciations\/init",
			"user_get_available_paths": "\/Path\/GetAvailablePaths\/init",
			"parent_get_settings_language_setting": "\/Parent\/GetParentSettingsLanguage\/init",
			"parent_set_settings_language_setting": "\/Parent\/SetParentSettingsLanguage\/init",
			"user_set_assessment_tour_status": "\/User\/SetAssessmentTourStatus\/init",
			"user_start_assessment_center": "\/User\/StartAssessmentCenter\/init",
			"parent_get_my_account_info": "\/Parent\/GetMyAccountInfo\/init",
			"parent_set_my_account_info": "\/Parent\/SetMyAccountInfo\/init",
			"parent_get_subscription_info": "\/Parent\/GetSubscriptionInfo\/init",
			"parent_get_billing_info": "\/Parent\/GetBillingInfo\/init",
			"parent_get_transaction_history": "\/Parent\/GetTransactionHistory\/init",
			"parent_update_account_password": "\/Parent\/UpdateAccountPassword\/init",
			"parent_update_billing_method": "\/Parent\/UpdateBillingMethod\/init",
			"popup_enumerate": "\/Popup\/Enumerate\/init",
			"popup_respond": "\/Popup\/Respond\/init",
			"my_room_save_avatar_state": "\/MyRoom\/SaveAvatarState\/init",
			"my_room_save_last_location": "\/MyRoom\/SaveLastLocation\/init",
			"my_room_get_info": "\/MyRoom\/GetInfo\/init",
			"my_room_save_item_state": "\/MyRoom\/SaveItemState\/init",
			"my_room_set_room_property": "\/MyRoom\/SetRoomProperty\/init",
			"my_room_get_room_list": "\/MyRoom\/GetRoomList\/init",
			"my_room_buy_room": "\/MyRoom\/BuyRoom\/init",
			"teacher_get_linked_students": "\/Teacher\/GetLinkedStudents\/init",
			"teacher_get_assessment_summary_results": "\/Teacher\/GetAssessmentSummaryResults\/init",
			"user_get_assessment_modal_warnings": "\/User\/GetAssessmentModalWarnings\/init",
			"user_get_notifications": "\/User\/GetNotifications\/init",
			"user_dismiss_notifications": "\/User\/DismissNotifications\/init",
			"holiday_win_prize": "\/Holiday\/WinPrize\/init",
			"assessment_get_next_screen": "\/Assessment\/GetNextScreen\/init",
			"user_jump_to_path_level": "\/User\/JumpToPathLevel\/init",
			"live_stream_register": "\/LiveStream\/Register\/init",
			"live_stream_get_user_event_info": "\/LiveStream\/GetUserEventInfo\/init"
		},
		"api_domains": {
			"site_root_url": "' . $url . '",
			"cdn_root_url": "' . $url . '\/artwork",
			"cdn_content_root_url": "' . $url . '\/content",
			"userart_root_url": "' . $url . '\/userart",
			"api_root_url": "' . $url . '\/api-member\/apis\/abc\/0.1\/json",
			"member_root_url": "' . $url . '\/member"
		},
		"action": {
			"generic_example_for_all_platforms": "Everybody sees this one"
		},
		"store": [],
		"analytics_info": {
			"target_offset": 28800
		},
		"server_timestamp": 1497074004,
		"server_timezone": "America\/Los_Angeles",
		"server_timezone_offset": -25200
	}
}';

echo $json;

?>
